# Generated by Django 3.2.16 on 2023-01-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='img',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
